sudo: false
language: ruby
rvm:
- 2.3.1
jdk:
- oraclejdk8
env:
  global:
  - export LC_CTYPE=ja_JP.UTF-8
  - GIT_COMMITTER_NAME=kubosho_
  - GIT_COMMITTER_EMAIL=ta2@o2p.jp
  - GIT_AUTHOR_NAME=o2project
  - GIT_AUTHOR_EMAIL=admin@o2p.jp
  - NODEJS_VER=6.10.0
  - secure: BWcVOpzd2qIvdM1EbDXpjRYN465e1gU2qVG0GJeVy0ZiYfei02m0AF45UALLQ4DvAYpb2DFtqf8MQ4KN4PC7UdiAoo+1bUvm0f2/i2uNRHkKdkIWE4QPBx/1NUNAKHlk3qZE6qw2acL1cgd8I9MM/cDwP8hGOkTg8ozxS19g0IBxg4n8iP5kJSY6qIaIfNiuH0630nFFfOHKcUckfseRgg+Q8qtam122UyzYsnNgnWrNDmTZrBg6eEBaZ3ExoMHh9JBuRi8ZvQ+j9t45u/ylZqsn/qgyXliv/UYyuWb3ylIZkE3lrTnV4eoOZiRnnETsjY9ggswvxmhf+NWRc09hWj3zeULGmyHn/rAb/FYtqxq1lQ9YXKMA17vaFMD6ESmNsw0WPDBEs/9l5NgwM2pEnJzGPYKDWz8P083kK6sK4Si+FZq/RXQMWaF/cXtFN7zdZDCc/GNyfBfV2Rq/SNqjVd80eF04UxWlUiIM99/NQUqUel3KeNj/Sf+vu89fQ/Kt/AQrSLnmpZyrtkeuL+xRqXoJHfX7fjem3RagmVwfp5QMweSDaEsfS1mM72wmn0th92dWJPamrlSwsK5S91GU4R/RLdamb3xzEWZEhFQ2lNEEzcH7+7PkgUVvvEEi2+cDha4AuFImrHrPqvhvNii9LKsq4AblAIX2eyoNk10xYdE=
before_install:
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_7679637290e0_key -iv $encrypted_7679637290e0_iv -in travis_key.enc -out .travis_rsa -d
- cp .travis_rsa ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
install:
- nvm install $NODEJS_VER
- nvm use $NODEJS_VER
- npm run setup
script:
- npm test
cache:
  directories:
  - vendor/bundle
  - node_modules
after_success:
- '[ "$TRAVIS_BRANCH" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "$GH_TOKEN" ] && npm run deploy'
