# review-epubmaker向けの設定ファイルの例。
# yamlファイルをRe:VIEWファイルのある場所に置き、
# 「review-epubmaker yamlファイル」を実行すると、<bookname>.epubファイルが
# 生成されます。
# このファイルはUTF-8エンコーディングで記述してください。

# この設定ファイルでサポートするRe:VIEWのバージョン番号。
# major versionが違うときにはエラーを出す。
review_version: 2.0

# ブック名(ファイル名になるもの。ASCII範囲の文字を使用)
bookname: book
# 記述言語。省略した場合はja
language: ja

# 書名
# 読みを入れる例 booktitle: {name: "Re:VIEW EPUBサンプル", file-as: "リビューイーパブサンプル"}
booktitle: Reset CSSフレンズ

# 著者名。「, 」で区切って複数指定できる
# 読みを入れる例 aut: [{name: "青木峰郎", file-as: "アオキミネロウ"}, {name: "武藤健志", file-as: "ムトウケンシ"}, {name: "高橋征義", file-as: "タカハシマサヨシ"}, {name: "角征典", file-as: "カドマサノリ"}]
aut: O2 Project
edt: kubosho_
dsr: kino
ill: tomo_e
prt: ねこのしっぽ

# 刊行日(省略した場合は実行時の日付)
date: 2017-04-09
# 発行年月。YYYY-MM-DD形式による配列指定。省略した場合はdateを使用する
# 複数指定する場合は次のように記述する
# [["初版第1刷の日付", "初版第2刷の日付"], ["第2版第1刷の日付"]]
# 日付の後ろを空白文字で区切り、任意の文字列を置くことも可能。
history: [["2017-04-09"]]
# 権利表記(配列で複数指定可)
rights: (C) 2017 O2 Project

# デバッグフラグ。nullでないときには一時ファイルをカレントディレクトリに作成し、削除もしない
debug: null

# 固有IDに使用するドメイン。指定しない場合には、時刻に基づくランダムUUIDが入る
urnid: urn:uid:http://friends.o2p.jp/

# Webページ用のディレクトリ指定（既定はwebroot）
docroot: "book"

# CSSファイル(配列で複数指定可)
stylesheet: ["style.css"]

# ePUBのバージョン (2か3)
epubversion: 3

# HTMLのバージョン (4か5。epubversionを3にしたときには5にする)
htmlversion: 5

# 目次として抽出する見出しレベル
toclevel: 2

# 採番の設定。採番させたくない見出しには「==[nonum]」のようにnonum指定をする
# 本文でセクション番号を表示する見出しレベル
secnolevel: 2

# 本文中に目次ページを作成するか。省略した場合はnull (作成しない)
toc: true

# 表紙にするHTMLファイル。ファイル名を指定すると表紙として入る
# cover: null

# 裏表紙ファイル (画像はcoversまたはimagesに配置する)。ファイル名を指定すると裏表紙として入る
# backcover: null

# 表紙に配置し、書籍の影絵にも利用する画像ファイル。省略した場合はnull (画像を使わない)。画像ディレクトリ内に置いてもディレクトリ名は不要(例: cover.jpg)
coverimage: null

# 奥付を作成するか。デフォルトでは作成されない。trueを指定するとデフォルトの奥付、ファイル名を指定するとそれがcolophon.htmlとしてコピーされる
colophon: true

# 1ページの行数文字数と1kbごとのページ数を用紙サイズで指定する(A5 or B5)。
page_metric: B5

epubmaker:
  # HTMLファイルの拡張子
  htmlext: xhtml
  # EPUBで表紙をコンテンツに含めるか。デフォルトでは作成されない。yesにするとiBooks等でも最初に表紙が表示されるようになる
  cover_linear: yes

# LaTeX用のスタイルファイル(styディレクトリ以下に置くこと)
texstyle: techbooster-doujin

# LaTeX用のdocumentclassを指定する
texdocumentclass: ["jsbook", "b5j,uplatex,twoside,openany"]

pdfmaker:
  colophon: true

webmaker:
  analytics:
    google: UA-25380313-9
